name: flutter_app_template
description: A template Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter

  # Internationalization
  flutter_localizations:
    sdk: flutter

  # Serialization
  json_annotation: ^4.6.0

  # Networking
  chopper: ^4.0.5

  # Logging
  logging: ^1.0.2

  # State management
  flutter_riverpod: ^1.0.4

  # Data classes
  freezed_annotation: ^2.0.3

  # Persistence
  shared_preferences: ^2.0.13
  flutter_secure_storage: ^5.0.2 # Note KeyStore was introduced in Android 4.3 (API level 18). The plugin wouldn't work for earlier versions.
  hive: ^2.0.6
  hive_flutter: ^1.1.0

  # Routing
  auto_route: ^4.2.1
  # go_router

  # UI
  pull_to_refresh: ^2.0.0

  # DI
  get_it: ^7.2.0

# Development packages
dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter

  # Code generation 
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  chopper_generator: ^4.0.5
  freezed: 2.0.3+1 # TODO: обновить зависимость
  hive_generator: ^1.1.2
  auto_route_generator: ^4.2.0

  # Linting
  flutter_lints: ^2.0.1
  dart_code_metrics: ^4.16.0

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

# Flutter Intl IDE extension    
flutter_intl:
  enabled: true # Required. Must be set to true to activate the plugin. Default: false
  class_name: S # Optional. Sets the name for the generated localization class. Default: S
  main_locale: en # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
  arb_dir: lib/assets/strings/arb # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
  output_dir: lib/assets/strings # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated
  use_deferred_loading: false # Optional. Must be set to true to generate localization code that is loaded with deferred loading. Default: false